### ISSUE TITLE
src/libmatrix/program.h fix build with gcc-12.1

### ISSUE THREAD

**Issue by jospezial** [glmark2/glmark2#176]
Build fails with gcc-12.1 on Gentoo:
```In file included from ../glmark2-2021.12/src/scene.h:33,
                 from ../glmark2-2021.12/src/benchmark.h:29,
                 from ../glmark2-2021.12/src/benchmark-collection.h:27,
                 from ../glmark2-2021.12/src/benchmark-collection.cpp:23:
../glmark2-2021.12/src/libmatrix/program.h: In constructor ‘Shader::Shader(Shader&&)’:
../glmark2-2021.12/src/libmatrix/program.h:39:22: error: ‘exchange’ is not a member of ‘std’
   39 |         handle_(std::exchange(shader.handle_, 0)),
      |                      ^~~~~~~~
../glmark2-2021.12/src/libmatrix/program.h:40:20: error: ‘exchange’ is not a member of ‘std’
   40 |         type_(std::exchange(shader.type_, 0)),
      |                    ^~~~~~~~
../glmark2-2021.12/src/libmatrix/program.h:43:21: error: ‘exchange’ is not a member of ‘std’
   43 |         ready_(std::exchange(shader.ready_, false)),
      |                     ^~~~~~~~
../glmark2-2021.12/src/libmatrix/program.h:44:21: error: ‘exchange’ is not a member of ‘std’
   44 |         valid_(std::exchange(shader.valid_, false)) {}
      |                     ^~~~~~~~
```
fixing diff for src/libmatrix/program.h:

```
#include <string>
+#include <utility>
#include <vector>
#include <map>
#include "mat.h"
```

**Comment by ftb4** [comment]
confirmed on arch for aur using yay as aur-manager
manual build from source works with above fix

**Comment by afrantzis** [comment]
Hi, this is a duplicate of #169, fix already applied at d1ca3f53c96dc8a4048b17dc16147a8fac782d4a. Thanks!
